// packages/react/src/index.tsx
'use client'
import { useEffect, useRef, useState, type CSSProperties, type ReactNode } from 'react'
import { CRT, type CRTOptions, type CRTScreen as Screen, type Quality, type Renderer } from 'retro-crt'

export interface CRTScreenProps extends CRTOptions {
  children?: ReactNode
  className?: string
  style?: CSSProperties
  /** Fires when the resolved renderer or quality changes (auto-detection, runtime downgrade). */
  onRendererChange?: (renderer: Renderer, quality: Quality) => void
}

export function CRTScreen({ children, className, style, onRendererChange, ...options }: CRTScreenProps) {
  const host = useRef<HTMLDivElement>(null)
  const [screen, setScreen] = useState<Screen | null>(null)
  const key = JSON.stringify(options)

  useEffect(() => {
    const el = host.current
    if (!el) return
    const s = CRT.mount(el, options)
    setScreen(s)
    return () => s.destroy()
    // Options flow through the update effect below; remounting on each change would be wasteful.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => screen?.set(JSON.parse(key)), [screen, key])

  useEffect(() => {
    if (!screen || !onRendererChange) return
    onRendererChange(screen.activeRenderer, screen.activeQuality)
    return screen.subscribe((s) => onRendererChange(s.activeRenderer, s.activeQuality))
  }, [screen, onRendererChange])

  return (
    <div ref={host} className={className} style={style}>
      <div data-rcrt-content="">{children}</div>
    </div>
  )
}

export type { CRTOptions, Quality, Renderer }

// packages/solid/src/index.tsx
import { createEffect, onCleanup, onMount, splitProps, type JSX } from 'solid-js'
import { CRT, type CRTOptions, type CRTScreen as Screen, type Quality, type Renderer } from 'retro-crt'

export interface CRTScreenProps extends CRTOptions {
  children?: JSX.Element
  class?: string
  style?: JSX.CSSProperties | string
  onRendererChange?: (renderer: Renderer, quality: Quality) => void
}

export function CRTScreen(props: CRTScreenProps) {
  const [local, options] = splitProps(props, ['children', 'class', 'style', 'onRendererChange'])
  let host: HTMLDivElement | undefined
  let screen: Screen | undefined
  // Serialising reads every nested prop, so the effect tracks the whole config.
  const snapshot = (): CRTOptions => JSON.parse(JSON.stringify(options))

  onMount(() => {
    if (!host) return
    const s = CRT.mount(host, snapshot())
    const notify = () => local.onRendererChange?.(s.activeRenderer, s.activeQuality)
    onCleanup(s.subscribe(notify))
    notify()
    screen = s
  })
  createEffect(() => {
    const next = snapshot()
    screen?.set(next)
  })
  onCleanup(() => screen?.destroy())

  return (
    <div ref={host} class={local.class} style={local.style}>
      <div data-rcrt-content="">{local.children}</div>
    </div>
  )
}

export type { CRTOptions }
